# Generated by Django 2.2.2 on 2019-07-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0002_auto_20190719_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnews',
            name='tag_news',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='allnews',
            name='text_news',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='allnews',
            name='title',
            field=models.CharField(max_length=360),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zavodnews.Allnews')),
            ],
        ),
    ]
