# Generated by Django 2.2.2 on 2019-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0003_auto_20190719_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnews',
            name='image_news',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
