# Generated by Django 2.2.2 on 2019-07-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0008_auto_20190720_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnews',
            name='image_news',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='Изображение'),
        ),
    ]
