# Generated by Django 2.2.2 on 2019-07-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0011_auto_20190720_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='eximg',
            new_name='ex_img',
        ),
    ]
