# Generated by Django 2.2.2 on 2019-07-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0012_auto_20190720_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
