# Generated by Django 2.2.2 on 2019-07-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0013_delete_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=360, unique=True, verbose_name='теги')),
            ],
        ),
        migrations.AddField(
            model_name='allnews',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='zavodnews.Keywords', verbose_name='теги'),
        ),
    ]
