# Generated by Django 2.2.2 on 2019-07-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0014_auto_20190721_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allnews',
            name='tag_news',
        ),
    ]
