# Generated by Django 2.2.2 on 2019-07-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0015_remove_allnews_tag_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allnews',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
