# Generated by Django 2.2.2 on 2019-07-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavodnews', '0016_auto_20190721_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allnews',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
